# Generated by Django 2.1.3 on 2018-11-10 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlnews',
            name='kelas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='skripsi.Kelas'),
        ),
    ]
