# Generated by Django 2.0.3 on 2018-09-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlDetikNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(blank=True)),
                ('date', models.CharField(max_length=50)),
                ('main_headline', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('stemming', models.TextField(blank=True)),
                ('stopword', models.TextField(blank=True)),
                ('sum_all_word', models.TextField(blank=True)),
                ('count_term', models.TextField(blank=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skripsi.Kelas')),
            ],
        ),
    ]
