# Generated by Django 2.0.3 on 2018-09-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0002_crawldetiknews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlDetikNews',
            new_name='CrawlNews',
        ),
    ]
