# Generated by Django 2.0.3 on 2018-10-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0003_auto_20180918_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlnews',
            name='kluster',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
