# Generated by Django 2.0.3 on 2018-10-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skripsi', '0004_crawlnews_kluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlnews',
            name='kluster',
            field=models.TextField(blank=True),
        ),
    ]
